# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56fab8e9bf699456c7a69d2ebfd5d778c0bdc7f5faebc0dd328d23dc11d7937e1fea36ef54e6d929ba5e28f6e55f6e697afa4fc1daee8e13f37be7b1e4ca03f4

test:
  secret_key_base: e35be0b3bf2fef03246680899c2850eb5a905f60bd0071ddd516304bdd829834d2d6572a10ff3a4177c503044db7c1992f53552692ece6caf8c7670eae443bee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
